package de.pho.dsapdfreader.config;

public enum TopicEnum
{
    TRICKS,
    SPELLS,
    RITUALS,
  BLESSINGS,
  LITURGIES,
  CEREMONIES,
  CURSES,
  ELFENSONGS,
  MELODIES,
  DANCES,
  MYSTICAL_SKILL_VARIANTS,
  MYSTICAL_SKILL_COMMONNESS,
  MERITS,
  FLAWS,
  SPECIAL_ABILITY_MUNDANE,
  SPECIAL_ABILITY_FATE,
  SPECIAL_ABILITY_COMBAT,
  SPECIAL_ABILITY_MAGIC,
  SPECIAL_ABILITY_CLERIC,
  SPECIAL_ABILITY_CLERIC_BASE,
  PROFESSIONS,
}
