package de.pho.dsapdfreader.exporter.model;

public enum TraditionKey
{
    all,
    angrosch,
    animist,
    aves,
    barde,
    boron,
    druid,
    efferd,
    elf,
    firun,
    geode,
    mage,
    goblin,
    hesinde,
    witch,
    ifirn,
    ingerimm,
    intuitive,
    kor,
    cristallomancer,
    levthan,
    marbo,
    gifted,
    namenlos,
    nandus,
    peraine,
    phex,
    praios,
    qabalya,
    rahja,
    rondra,
    shaman_all,
    illusionist,
    harlequin,
    swafnir,
    travia,
    tsa,
    alchimist,
    dancer,
    zibilja,
    shaman_ferkina, shaman_fjarninger, shaman_gjalsker, shaman_moha, shaman_nivese, shaman_trollzacker, brobim_geode
}
