package de.pho.dsapdfreader.exporter.model.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ArmorKey
{
  iryanruestung,
  kettenhemd,
  kroetenhaut,
  lederharnisch,
  leichte_platte,
  schuppenpanzer,
  spiegelpanzer,
  tuchruestung,
  amazonen_ruestung,
  bronzeharnisch,
  eisenmantel,
  fellruestung,
  fuenflagenharnisch,
  gambeson,
  garether_platte,
  gestechruestung,
  gladiatoren_ruestung,
  hartholz_harnisch,
  hornruestung,
  ifirnsmantel,
  kettenweste,
  kuerass,
  kurbul,
  lamellar,
  langes_kettenhemd,
  lindwurmhaut,
  mammuton_panzer,
  reiterharnisch,
  schuppen_gewand,
  schwere_platte,
  skorpionhemd,
  turnierruestung,
  wattierter_waffenrock,
  normale_kleidung_felle_oder_nackt,
  schwere_kleidung_winterkleidung,
  stoffruestung_gambeson,
  lederruestung,
  kettenruestung,
  schuppenruestung,
  plattenruestung,
  olporter_kroetenhaut,
  premer_schuppenpanzer,
  thorwalerhelm,
  gjalsker_lederruestung_lathairmach,
  elburische_tuchruestung,
  der_baburische_spiegelpanzer,
  zorganer_ringelpanzer,
  skorpionruestung,
  havener_lederharnisch,
  matrosenkleidung,
  brigantina,
  seekriegerruestung,
  neethaner_reiterharnisch,
  koscher_gambeson,
  albenhuser_plattenharnisch,
  nordmaerker_ritterruestung,
  isnatoscher_kettengeflecht,
  die_keke_chitinruestung,
  keke_chitinruestung_keke_mako,
  miniwatu_lederharnisch_watu_mako,
  epharit_ruestung_gumijok_mano,
  ferkina_fellruestung,
  lederruestung_der_beni_geraut_schie,
  mherweder_ringelpanzer,
  novadischer_waffenrock,
  ;


  @JsonValue
  public int toValue()
  {
    return ordinal();
  }
}
