package de.pho.dsapdfreader.exporter.model.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ArmorKey {
  iryanruestung,
  kettenhemd,
  kroetenhaut,
  lederharnisch,
  leichte_platte,
  schuppenpanzer,
  spiegelpanzer,
  tuchruestung,
  amazonenruestung,
  bronzeharnisch,
  eisenmantel,
  fellruestung,
  fuenflagenharnisch,
  gambeson,
  garether_platte,
  gestechruestung,
  gladiatorenruestung,
  hartholzharnisch,
  hornruestung,
  ifirnsmantel,
  kettenweste,
  kuerass,
  kurbul,
  lamellar,
  langes_kettenhemd,
  lindwurmhaut,
  mammutonpanzer,
  reiterharnisch,
  schuppengewand,
  schwere_platte,
  skorpionhemd,
  turnierruestung,
  wattierter_waffenrock,
  normale_kleidung_felle_oder_nackt,
  schwere_kleidung_winterkleidung,
  stoffruestung_gambeson,
  lederruestung,
  kettenruestung,
  schuppenruestung,
  plattenruestung,
  olporter_kroetenhaut,
  premer_schuppenpanzer,
  thorwalerhelm,
  gjalsker_lederruestung_lathairmach,
  elburische_tuchruestung,
  baburische_spiegelpanzer,
  zorganer_ringelpanzer,
  skorpionruestung,
  havener_lederharnisch,
  matrosenkleidung,
  brigantina,
  seekriegerruestung,
  neethaner_reiterharnisch,
  koscher_gambeson,
  albenhuser_plattenharnisch,
  nordmaerker_ritterruestung,
  isnatoscher_kettengeflecht,
  keke_chitinruestung,
  keke_chitinruestung_keke_mako,
  miniwatu_lederharnisch_watu_mako,
  epharit_ruestung_gumijok_mano,
  ferkina_fellruestung,
  lederruestung_der_beni_geraut_schie,
  mherweder_ringelpanzer,
  novadischer_waffenrock,
  bornische_eisenmantel,
  goblinische_fellweste,
  maerker_kettenhemd,
  neersander_gambeson,
  norbardische_ledermantel,
  sewerischer_fluegelharnisch,
  knochenruestung,
  pantherruestung,
  ringelpanzer;


  @JsonValue
  public int toValue() {
    return ordinal();
  }
}
