package de.pho.dsapdfreader.exporter.model.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ElixierKey {
    trunk_der_ruhigen_hand,
    alchimistensaeure,
    antidot,
    bannstaub,
    berserkerelixier,
    eulentraenen,
    heiltrank,
    hylailer_feuer,
    kaltes_licht,
    leuchtkreide,
    liebestrunk,
    pastillen_gegen_schmerzen,
    pyrophor,
    schlaftrunk,
    schwadenbeutel,
    stinktoepfchen,
    unsichtbarkeitselixier,
    verwandlungselixier,
    waffenbalsam,
    wasserodem,
    willenstrunk,
    zaehigkeitstrunk,
    zaubertrank,
    zielwasser,
    tausend_und_ein_rausch,
    bannkreide,
    charismaelixier,
    erscheinungspulver,
    feuerpulver,
    fingerfertigkeitselixier,
    friedenswasser,
    furchtlos_tropfen,
    gewandtheitselixier,
    ghulscheuche,
    gnaediger_drachenodem,
    hauch_der_weissagung,
    heilsalbe,
    ifirnstrunk,
    konstitutionselixier,
    koerperkraftelixier,
    lotostrunk,
    magiepaste,
    mengbiller_bannbaloel,
    mutelixier,
    neckergel,
    pulver_des_klaren_geistes,
    quasselpulver,
    scharfsinnelixier,
    schmerzwein,
    tarnelixier,
    techtals_elixier,
    tharvun_parfuem,
    tijakools_hauch,
    unverwundbarkeitselixier,
    wachtrunk,
    weissagungspulver,
    zurbarans_pflanzentinktur,
    alkahest,
    anderswelt_lidschatten,
    rote_leu,
    elixier_der_stille,
    erdkraft_lack,
    fatas_tabak,
    goettlicher_balsam,
    nebelfarbe,
    peraines_kleine_gnade,
    rachenputzer,
    respondarum,
    seifenblasen_packesel,
    sonnenlicht_elixier,
    synaerethikon,
    trank_der_gottesnaehe,
    trank_der_tausend_augen;

    @JsonValue
    public int toValue() {
        return ordinal();
    }
}
