package de.pho.dsapdfreader.exporter.model.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum LanguageKey {
  alaani,
  alt_imperial_alt_güldenländisch_aureliani,
  amuurak,
  angram,
  archäisch,
  asdharia,
  atak,
  bosparano,
  bukanisch,
  drachisch,
  draydalanisch,
  dschuku,
  ferkina,
  fjarningisch,
  früh_imperial,
  garethi,
  gemein_amaunal,
  gemein_imperial,
  gjalskisch,
  goblinisch,
  golp,
  goropo,
  grolmisch,
  grolmurisch,
  hiero_amaunal_ahmagao,
  hiero_imperial,
  hjaldingisch_saga_thorwalsch,
  hoch_gryphonisch,
  hummerisch,
  isdira,
  kemi,
  khami,
  kherrishitisch,
  koboldisch,
  krakonisch,
  leonal_khorrzu,
  loualilisch,
  mahrisch,
  tahaya,
  molochisch,
  myranisch,
  nathani,
  neckergesang,
  neristal,
  nujuka,
  ogrisch,
  oloarkh,
  ologhaijan,
  pardiral_bhagrach,
  petraya,
  rabensprache,
  riesensprache,
  rissoal,
  rogolan,
  rssahh,
  rsssah_dra,
  ruuz,
  schwarz_gryphonisch,
  shingwanisch,
  shinoq,
  thorwalsch,
  tiefzwergisch,
  trollisch,
  tulamidya,
  ur_tulamidya,
  uthurisch,
  vinshinisch,
  xoxota,
  yetan,
  zelemja,
  zhayad,
  zhulchammaqra,
  z_lit,
  zyklopäisch,
  zyklopisch,
  adorunu;

  @JsonValue
  public int toValue() {
    return ordinal();
  }

}
