package de.pho.dsapdfreader.exporter.model.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Publication {

  almanach,
  basis,
  bote,
  eiserne_flammen,
  katakomben_und_ruinen,
  kompendium_1,
  kompendium_2,
  magie_1,
  magie_2,
  magie_3,
  siebenwindkueste,
  streitende_koenigreiche,
  unbekannt,
  ruestkammer_1,
  buendnis_der_wacht,
  der_weisse_see,
  schirm,
  namen,
  hausregel,
  glaube_macht_und_heldenmut,
  goetter_1,
  goetter_2,
  klingen_der_nacht,
  bestiarium_1,
  bestiarium_2,
  kneipen_und_tavernen,
  flusslande,
  gefangen_in_der_gruft_der_koenigin,
  ruestkammer_2,
  dornenreich,
  der_dunkle_mhanadi,
  havena,
  die_silberne_wehr,
  herbarium_1,
  herbarium_2,
  grimorium,
  kodex_der_magie,
  kodex_des_schwertes,
  strassenstaub_und_halsabschneider,
  kodex_der_helden,
  ruestkammer_des_dornenreiches,
  ruestkammer_der_gestade_des_gottwals,
  ruestkammer_der_siebenwindkueste,
  ruestkammer_der_sonnenkueste,
  ruestkammer_der_flusslande,
  ruestkammer_der_dampfenden_dschungel,
  ruestkammer_der_streitenden_koenigreiche,
  ruestkammer_der_wuestenreiche,
  kodex_des_goetterwirkens,
  divinarium,
  arkane_schmiede,
  helden_des_gottwals,
  gestade_des_gottwals,
  helden_der_flusslande,
  die_flusslande,
  helden_der_winterwacht,
  die_winterwacht,
  helden_des_dornenreiches,
  das_dornenreich,
  kodex_der_kaeuter,
  archiv_der_ausruestung,
  geschoepfe_der_anderswelt,
  die_echsensuempfe,
  helden_der_echsensuempfe,
  aventurische_tiergefaehrten,
  geschuppte_tyrannen,
  aventurisches_elementarium,
  archiv_der_kraeuter,
  gmuh_die_streitenden_koenigreiche,
  archiv_der_kreaturen,
  archiv_der_daemonen,
  helden_der_siebenwindkueste,
  helden_des_wolfsfrosts,
  weltenwanderer,
  aventurisches_nekromantaeum,
  aventurisches_transmutarium,
  fluestern_aus_dem_abgrund,
  gmuh_havena,
  aventurisches_animatorium,
  eiserne_flamme,
  gmuh_dampfende_dschungel,
  gmuh_sonnenkueste;


  @JsonValue
  public int toValue() {
    return ordinal();
  }

}
