package de.pho.dsapdfreader.exporter.model.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Publication
{

  Almanach,
  Basis,
  Bote,
  Eiserne_Flammen,
  Katakomben_und_Ruinen,
  Kompendium_1,
  Kompendium_2,
  Magie_1,
  Magie_2,
  Magie_3,
  Siebenwindküste,
  Streitende_Königreiche,
  Unbekannt,
  Rüstkammer_1,
  Buendnis_der_Wacht,
  Der_weisse_See,
  Schirm,
  Namen,
  Hausregel,
  Glaube_Macht_und_Heldenmut,
  Götter_1,
  Götter_2,
  Klingen_der_Nacht,
  Bestiarium_1,
  Bestiarium_2,
  Kneipen_und_Tavernen,
  Flusslande,
  Gefangen_in_der_Gruft_der_Königin,
  Rüstkammer_2,
  Dornenreich,
  Der_dunkle_Mhanadi,
  Havena,
  Die_silberne_Wehr,
  Herbarium_1,
  Herbarium_2,
  Grimorium,
  Kodex_der_Magie,
  Kodex_des_Schwertes,
  Strassenstaub_und_Halsabschneider,
  Kodex_der_Helden,
  Rüstkammer_des_Dornenreiches,
  Rüstkammer_der_Gestade_des_Gottwals,
  Rüstkammer_der_Siebenwindküste,
  Rüstkammer_der_Sonnenküste,
  Rüstkammer_der_Flusslande,
  Rüstkammer_der_dampfenden_Dschungel,
  Rüstkammer_der_streitenden_Königreiche,
  Rüstkammer_der_Wüstenreiche,
  Kodex_des_Götterwirkens,
  Divinarium,
  Arkane_Schmiede,
  Helden_des_Gottwals,
  Gestade_des_Gottwals,
  Helden_der_Flusslande,
  Die_Flusslande,
  Helden_der_Winterwacht,
  Die_Winterwacht,
  Helden_des_Dornenreiches,
  Das_Dornenreich,
  Kodex_der_Käuter,
  Archiv_der_Ausrüstung,
  Geschöpfe_der_Anderswelt,
  Die_Echsensümpfe,
  Helden_der_Echsensümpfe,
  Aventurische_Tiergefährten,
  Geschuppte_Tyrannen,
  Aventurisches_Elementarium,
  Archiv_der_Kräuter,
  GMuH_Die_streitenden_Königreiche,
  Archiv_der_Kreaturen,
  Archiv_der_Dämonen,
  Helden_der_Siebenwindküste,
  Helden_des_Wolfsfrosts,
  Weltenwanderer,
  Aventurisches_Nekromantäum,
  Aventurisches_Transmutarium;


  @JsonValue
  public int toValue() {
    return ordinal();
  }

}
